name: Build And Deploy - Staging

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      env:
        working-directory: ./src/Tetris
      steps:
      - name: Checkout Main
        uses: actions/checkout@v3.5.2

      - name: .NET Core setup
        uses: actions/setup-dotnet@3.2.0
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o ./publish
        working-directory: ${{ env.working-directory }}

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to aws
        run: aws s3 sync ./publish/wwwroot s3://blazor-tetris-20230913142421969200000002 --delete