name: deploy-infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-main
        uses: actions/checkout@v4.2.2

      - name: configure-aws
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: pulumi-deploy
        uses: pulumi/actions@v6.0.0
        with:
          command: update
          stack-name: foflores/blazorTetris/main
          work-dir: ./BlazorTetris.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
