name: deploy-production

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3.5.2

      - name: .NET Core setup
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '8.0.10'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o ./publish
        working-directory: ./BlazorTetris

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::633067888675:role/infrastructure-production-roleIac-f6bb1a9

      - name: Deploy to aws
        run: aws s3 sync ./publish/wwwroot s3://blazor-tetris-bucket20241024043754786000000001 --delete
        working-directory: ./BlazorTetris

      - name: Invalidate cdn
        run: aws cloudfront create-invalidation --distribution-id EB770A3529SNW --paths "/*"
