name: Deploy App

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - Dev
          - Prod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o ./publish
        working-directory: ./BlazorTetris

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Deploy to aws
        run: aws s3 sync ./publish/wwwroot s3://${{ vars.AWS_SOURCE_BUCKET }} --delete
        working-directory: ./BlazorTetris

      - name: Invalidate cdn
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_MAIN_DISTRIBUTION }} --paths "/*"
